Remove future imports
XML-Security/signxml pull request #179
Opened 2021-11-11 15:30 UTC by pokoli

Since https://github.com/XML-Security/signxml/commit/660c3b1692fb021fb4845f3a466c7b92037f1c49 support for python2 has been removed. So there is no need to keep using the `__future__` imports as such implementation is the default behaviour for python3.

2021-11-11 21:18 UTC, kislyuk requested changes

2021-11-11 21:18 UTC, kislyuk commented on test/test.py
> -sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
Please keep this line.

2021-11-19 11:53 UTC, pokoli commented
Is there anything else missing from my side? 
Tests haven't run as it requires as aproval from any maintainter.

2021-11-22 18:10 UTC, merged

2021-11-22 18:10 UTC, kislyuk commented
Looks good. Thank you for your contribution.