Added support for optional HMACOutputLength for hmac-sha signing & va…
XML-Security/signxml pull request #192
Opened 2022-08-15 07:52 UTC by eclhmf

…lidation.

2022-08-15 07:56 UTC, eclhmf commented
This pull request adds support for the optional HMACOutputLength parameter, which truncates the HMAC output digest. See https://www.w3.org/TR/xmldsig-core1/#sec-SignatureMethod.

2022-08-19 21:40 UTC, kislyuk requested changes
Thank you for your contribution.

Do you have a specific application that requires the use of this parameter? This parameter is a security hazard since it can be used in downgrade attacks. Moreover, your implementation introduces a downgrade attack vulnerability because it allows a malicious signer to downgrade ANY algorithm, not just the HMAC-SHA ones.

While I initially declined to implement `ds:HMACOutputLength` due to the security hazards associated with it, I can consider it as impelmented in this PR if the following issues are addressed:

* Document an interoperability rationale in the form of a library or other publicly distributed application that requires it
* Raise an `InvalidSignature` error if `ds:HMACOutputLength` appears with a signature method other than `HMAC-SHA*`
* Disable the use of `ds:HMACOutputLength` in `XMLVerifier.verify()` by default due to the security challenges it presents. Add a class variable or keyword argument, `allow_hmac_output_length`, set to False by default and configurable by the caller
* Add a test case asserting correct behaviors in all of the cases described above
* Enable all test vectors using `ds:HMACOutputLength` in the test suite and verify that they pass.

2022-08-19 21:40 UTC, kislyuk commented on signxml/__init__.py
> +                    raise InvalidInput('HMAC output length is too small')
This should be `InvalidSignature`

2022-11-06 16:43 UTC, kislyuk commented
We will not be implementing HMAC truncation or any peer-configurable signature or digest material truncation due to the security hazards inherent in such functionality. See https://www.w3.org/blog/2009/07/hmac-truncation-in-xml-signatu/ for further context.

2022-11-06 16:43 UTC, closed without merging