Add xades support
XML-Security/signxml pull request #199
Opened 2022-09-14 13:39 UTC by pokoli

Hi, 

Here is the implementation of [#90](https://github.com/XML-Security/signxml/issues/90)
For now we just include basic properties of xades but it works for simple implementations. 

I will like to have some feedback of the maintainers to now what is required to include this feature as part of a new release. Do we need full xades support or we can start which just basic functionalities? 

P.S: There are a lot of old commits here, do you think it makes sense to merge them into a single one to make the review easier?

2022-09-15 15:56 UTC, pokoli commented
Note that on last commit I use the default parameter of namedtuple which is only available on python 3.7. 
I've created #200 which removes support for Python 3.6, this is a requirement to allow merging this PR.

2022-09-16 04:37 UTC, kislyuk requested changes
This is a great start, thanks.

I have added a few comments inline. Please make sure there are no stray comments and unused code left behind. All methods should be used by other methods or documented as part of the public API.

Can you please add an interoperability ("interop") unit test case that verifies third party documents ("vectors") signed using xades? It looks like the following repos have a few test files:
* https://github.com/esig/dss/tree/master/dss-asic-xades/src/test/resources
* https://github.com/Ahmet-Kaplan/xades4j.interop/tree/master/src/test/resources/verification

2022-09-16 04:37 UTC, kislyuk commented on signxml/__init__.py
> +            self.cert_chain = list(iterate_pem(cert))
Please do not attach any signature-specific information to the signer/verifier instance. The instance is stateless.

2022-09-16 04:37 UTC, kislyuk commented on signxml/__init__.py
> +        :param reference_uris: the references to include o buld.
```suggestion
        :param reference_uris: the references to include or build.
```

2022-09-16 04:37 UTC, kislyuk commented on signxml/__init__.py
> +        def _check_brothers(element1, element2):
This doesn't seem to be used anywhere?

2022-09-16 04:37 UTC, kislyuk commented on signxml/xades/README.rst
> +`W3C Note: XML Advanced Electronic Signatures (XAdES) <https://www.w3.org/TR/XAdES>`_ is outdated and has aparently been superseeded by standard development by `ETSI <https://www.etsi.org/>`_.
```suggestion
`W3C Note: XML Advanced Electronic Signatures (XAdES) <https://www.w3.org/TR/XAdES>`_ is outdated and has apparently been superseded by standard development by `ETSI <https://www.etsi.org/>`_.
```

2022-09-16 04:37 UTC, kislyuk commented on signxml/xades/__init__.py
> +        # reference_uris.extend(self.refs)
```suggestion
```

2022-09-16 04:37 UTC, kislyuk commented on signxml/xades/__init__.py
> +                    # TODO implement, wtf?
```suggestion
                    # TODO: implement
```

2022-09-16 04:37 UTC, kislyuk commented on signxml/xades/__init__.py
> +                "Legay certified roles wired as objects encoded in " "EncapsulatedPKIDataType are not implemented."
```suggestion
                "Legacy certified roles wired as objects encoded in " "EncapsulatedPKIDataType are not implemented."
```

2022-09-16 04:37 UTC, kislyuk commented on signxml/xades/__init__.py
> +        # any ##other
```suggestion
```

2022-09-16 04:37 UTC, kislyuk commented on signxml/xades/__init__.py
> +        # any ##other
```suggestion
```

2022-09-16 04:37 UTC, kislyuk commented on signxml/xades/__init__.py
> +        # any ##other
```suggestion
```

2022-11-14 00:50 UTC, kislyuk commented
Thanks everyone for your work on this PR. XAdES support was added in v3.0.0 using a different code structure. Please test v3.0.0 and let us know whether it suits your needs.

2022-11-14 00:50 UTC, closed without merging

2022-11-14 01:16 UTC, ovnicraft commented
@kislyuk great news! any code recommended to read ? I would like to improve documentation and add some examples about XaDES

2022-11-14 01:17 UTC, ovnicraft commented
Found it http://xml-security.github.io/signxml/#xades-signatures !